### ISSUE TITLE
Add option for custom help pop ups for each data point and data source

### ISSUE THREAD

**Issue by Joelhaggar** [infiniteautomation/ma-core-public#122] opened 2014-04-25 19:45 UTC
Users can input custom html for information popups.  the "?" icon can be used when mouse over on a data point on watch list, graphic views and point details.  There could be a link on the data source page and data point edit page to upload the html.

**Comment by Puckfist** [comment] 2015-12-10 21:44
A long while ago I thought it would be cool if Mango had a user-edited sort of built-in wiki help, then integrate that with the company wiki and have some means of controlling what makes it into the master articles.

**Comment by Puckfist** [comment] 2016-11-13 16:16
Duplicate of #78 ?

**Closed** 2017-04-12 23:15 UTC
Labels: +8Hr, New Feature
