### ISSUE TITLE
Point copy or point add permissions not saved on new points

### ISSUE THREAD

**Issue by resotek** [infiniteautomation/ma-core-public#856] opened 2016-10-27 00:33 UTC
When a new point is created and then saved, the data from the permission field is cleared (and not saved). The permission fields must be re-entered and then another save operation must be performed. This is an issue whenever the admin desires a non-blank permission field.

**Comment by Puckfist** [comment] 2016-10-27 02:01
Duplicate of https://github.com/infiniteautomation/ma-core-public/issues/812 fixed in 2.8 or 2.7.14 when released

**Closed** 2016-10-27 22:44 UTC
