### ISSUE TITLE
Add support for multiple email addresses in User Preferences

### ISSUE THREAD

**Issue by resotek** [infiniteautomation/ma-core-public#89] opened 2014-03-30 17:42 UTC
Allow **comma-separated email addresses** in the User Preferences page. This will enable users to specify more than one email address for themselves. Benefits:

* Automatic support of backup email servers
* Automagically enable user to receive email on mobile phones in addition to email account, since the user can specify the free email address gateway of their mobile phone service provider using the [Email To SMS Email Address List](http://www.emailtextmessages.com/) without the overhead of setting up and managing recurring payments for using an email-to-sms service.

**Comment by Puckfist** [comment] 2015-12-10 22:43
Closing as duplicate of [issue 90](https://github.com/infiniteautomation/ma-core-public/issues/90)

**Closed by Puckfist** 2015-12-10 22:43 UTC
