### ISSUE TITLE
Spline Chart Artifacts on Legacy Data Point Details Page

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#676] opened 2016-03-11 21:54 UTC
Using this data on a numeric data point with a Spline plot type the plot does not accurately reflect the true data.  

By replacing the JFree renderer with a custom implementation the results are much better.

[test-peak.xlsx](https://github.com/infiniteautomation/ma-core-public/files/170011/test-peak.xlsx)

The new renderer should be tested for boundary conditions to ensure that it doesn't fail to render data.

See this commit: 398f50e4c81013c33419f56a11d6f91fa49dc302

**Comment by Puckfist** [comment] 2016-04-15 19:38
I am closing this. Two complaints were raised about an error in Range counting points, and reverting to .14 solved their issue. However, at least one of these was caused by an overridden class, and was resolved when he inspected his classpath more closely.

**Closed by Puckfist** 2016-04-15 19:38 UTC
Labels: Enhancement, Ready for Testing
